### ISSUE TITLE
expection with npm test

### ISSUE THREAD

**Issue by BhaskaranR** [dwyl/hapi-auth-jwt2-example#20]
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Object.Module._extensions.(anonymous function) [as .js](C:hapi-auth-jwt2-examplenode_modulesistanbullibhook.js:109:37)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at runFn (C:\hapi-auth-jwt2-example\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)

not sure if this is new to environment

**Comment by BhaskaranR** [comment]
not

**Comment by BhaskaranR** [comment]
i still get the error. I am running this on windows

**Comment by nelsonic** [comment]
@BhaskaranR what version of Node.js are you running?

**Comment by BhaskaranR** [comment]
I have node 4.2.6, it worked when i changed npm test to this--

istanbul cover node_modules/tape/bin/tape ./test/test.js -- -R spec

**Comment by nelsonic** [comment]
Ah, ok. feel free to send us a Pull Request updating it. 👍
